--- 
- name: Create apache2.service.d directory
  file:
    path: /etc/systemd/system/apache2.service.d/
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Make apache start after wireguard
  copy:
    content: |
      [Unit]
      After=wg-quick@{{ wireguard_interface_name }}.service
    dest: /etc/systemd/system/apache2.service.d/override.conf
    owner: root
    group: root
    mode: 0644
