---
- import_playbook: playbooks/common.yml
  vars:
    perform_full_upgrade: no
    install_common_tools: yes
    install_python_tools: yes
    install_media_tools: yes

- name: PiNAS setup
  hosts: pinas
  become: true

  vars_files:
    - secrets.yml

  vars:
    main_domain: "{{ duckdns_domain }}.duckdns.org"

    # Argon EON
    argoneon_rtc_service_enabled: no
    argoneon_fan_lcd_service_enabled: yes

    # Nextcloud
    nextcloud_db_name: nextcloud
    nextcloud_www_folder: /var/www
    nextcloud_data_directory: /srv/nextcloud
    nextcloud_php_memory_limit: 4G

    # Transmission
    transmission_download_dir: "/srv/transmission/downloads"
    transmission_incomplete_dir: "/srv/transmission/incomplete_downloads"
    transmission_incomplete_dir_enabled: true

    # Disks
    disks:
      - device: /dev/sda1
        path: /mnt/hdd500
        fs: ext4
      - device: /dev/sdb1
        path: /mnt/hdd750
        fs: ext4

    # Symlinks
    symlinks:
      - link: /srv/nextcloud
        src: /mnt/hdd500/nextcloud
      - link: /srv/transmission
        src: /mnt/hdd500/transmission

  roles:
    - argon-eon
    - duckdns
    - wireguard
    - nextcloud
    - transmission

  pre_tasks:
    - import_tasks: tasks/fstab/main.yml
    - import_tasks: tasks/symlinks/main.yml
    - import_tasks: tasks/raspi-reset/main.yml
    - import_tasks: tasks/letsencrypt/main.yml
    - import_tasks: tasks/apache/main.yml

  tasks:
    - import_tasks: tasks/reverse-proxy/main.yml
