---
- import_playbook: playbooks/common.yml
  vars:
    perform_full_upgrade: no
    install_common_tools: yes
    install_python_tools: yes
    install_media_tools: yes

- name: PiNAS setup
  hosts: pinas
  become: true

  vars_files:
    - vars/main.yml
    - vars/storage.yml
    - vars/secrets.yml

  roles:
    - argon-eon
    - duckdns
    - wireguard
    - nextcloud
    - transmission
    - syncthing

  pre_tasks:
    - import_tasks: tasks/fstab/main.yml
    - import_tasks: tasks/symlinks/main.yml
    - import_tasks: tasks/raspi-reset/main.yml
    - import_tasks: tasks/letsencrypt/main.yml
    - import_tasks: tasks/apache/main.yml

  tasks:
    - name: Disable sudo with no password
      file:
        path: /etc/sudoers.d/010_pi-nopasswd
        state: absent

    - name: Add user {{ username }} to groups {{ ', '.join(user_groups) }}
      user:
        name: "{{ username }}"
        groups: "{{ user_groups }}"
        append: yes

    - name: Add SSH keys
      authorized_key:
        user: "{{ username }}"
        key: "{{ lookup('file', '{{ item }}') }}"
        state: present
      loop: "{{ ssh_keys }}"
