---
- import_playbook: playbooks/common.yml
  tags: common
  vars:
    perform_full_upgrade: no
    install_common_tools: yes
    install_python_tools: yes
    install_media_tools: yes

- name: PiNAS setup
  hosts: pinas
  become: true

  vars_files:
    - vars/main.yml
    - vars/storage.yml
    - vars/secrets.yml

  roles:
    - { role: argon-eon, tags: argon }
    - { role: duckdns, tags: duckdns }
    - { role: wireguard, tags: wireguard }
    - { role: docker, tags: docker }
    - { role: lazydocker, tags: lazydocker }
    - { role: syncthing, tags: syncthing }
    - { role: transmission, tags: transmission }
    - { role: nextcloud, tags: nextcloud }

  pre_tasks:
    - { import_tasks: tasks/storage/main.yml, tags: storage }
    - { import_tasks: tasks/symlinks/main.yml, tags: symlinks }
    - { import_tasks: tasks/raspi-reset/main.yml, tags: raspi-reset }

  tasks:
    - { import_tasks: tasks/letsencrypt/main.yml, tags: letsencrypt }
    - { import_tasks: tasks/apache/main.yml, tags: apache }
    - { import_tasks: tasks/docker-containers/main.yml, tags: containers }
    - { import_tasks: tasks/playlist-sync/main.yml, tags: playlist-sync }

    - name: Disable sudo with no password
      tags: disable-sudo
      file:
        path: /etc/sudoers.d/010_pi-nopasswd
        state: absent

    - name: Add user {{ username }} to groups {{ ', '.join(user_groups) }}
      tags: groups
      user:
        name: "{{ username }}"
        groups: "{{ user_groups }}"
        append: yes

    - name: Add SSH keys
      tags: ssh-keys
      authorized_key:
        user: "{{ username }}"
        key: "{{ lookup('file', '{{ item }}') }}"
        state: present
      loop: "{{ ssh_keys }}"

    - name: Copy some dotfiles
      tags: dotfiles
      become: yes
      become_user: "{{ username }}"
      copy:
        src: "{{ item }}"
        dest: "{{ item }}"
      loop: "{{ dotfiles }}"
