---
- name: reload transmission-daemon
  service: name=transmission-daemon state=reloaded

- name: restart transmission-daemon
  service: name=transmission-daemon state=restarted

- name: reload and restart transmission-daemon
  service: name=transmission-daemon state=reloaded
  notify: restart transmission-daemon

- name: reload apache2
  service: name=apache2 state=reloaded

- name: restart apache2
  service: name=apache2 state=restarted
