---
- name: Create directories for symlinks targets
  file:
    path: "{{ item.target }}"
    state: directory
    owner: "{{ item.owner | default(omit) }}"
    group: "{{ item.group | default(omit) }}"
    mode: "{{ item.mode | default(omit) }}"
  loop: "{{ symlinks_dir }}"

- name: Create symlinks
  file:
    src: "{{ item.target }}"
    dest: "{{ item.link }}"
    state: link
    force: yes
    follow: no
    owner: "{{ item.owner | default(omit) }}"
    group: "{{ item.group | default(omit) }}"
    mode: "{{ item.mode | default(omit) }}"
  loop: "{{ symlinks_dir }}"
