---
- name: Install transmission-daemon
  apt: 
    name: transmission-daemon
    state: present
    update_cache: yes

- name: Enable transmission-daemon
  service:
    name: transmission-daemon
    state: started
    enabled: yes

- name: Copy transmission config file to /etc/transmission-daemon/settings.json
  template:
    src: settings.json.j2
    dest: /etc/transmission-daemon/settings.json
    owner: debian-transmission
    group: debian-transmission
    mode: 0600
  notify: reload and restart transmission-daemon

- meta: flush_handlers
