---
- name: Install unattended-upgrades
  apt:
    name: unattended-upgrades
    state: present

- name: Enable unattended-upgrades service
  service:
    name: unattended-upgrades
    state: started
    enabled: yes
