services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: always
    ports:
      - 127.0.0.1:{{ vaultwarden_port }}:80
    volumes:
      - /nas/appdata/vaultwarden:/data
    environment:
      DOMAIN: "https://{{ vaultwarden_domain }}"
      SIGNUPS_ALLOWED: false
      INVITATIONS_ALLOWED: false
      ADMIN_TOKEN: ${VAULTWARDEN_ADMIN_TOKEN}
      IP_HEADER: X-Forwarded-For
      LOG_FILE: /data/vaultwarden.log
      LOG_LEVEL: warn
      EXTENDED_LOGGING: true
