---
- name: Nextcloud install
  hosts: all
  become: yes

  vars:
    db_name: nextcloud
    db_username: nextcloud
    db_password: nextcloudpasswd
    download_url: https://download.nextcloud.com/server/releases/latest.tar.bz2
    checksum_url: sha256:https://download.nextcloud.com/server/releases/latest.tar.bz2.sha256
    download_path: /tmp/nextcloud.tar.bz2
    www_folder: /var/www
    data_directory: /srv/nextcloud
  
  pre_tasks:
    - name: Update apt cache
      apt: update_cache=true cache_valid_time=3600

  handlers:
    - name: reload apache2
      service: name=apache2 state=reloaded
    - name: restart apache2
      service: name=apache2 state=restarted

  tasks:
    - name: Install Apache, PHP and Postgresql
      apt: 
        name: apache2, php, postgresql, python3-psycopg2, acl
        state: present

    - name: Ensure Apache and Postgresql are started and enabled
      service:
        name: "{{ item }}"
        state: started
        enabled: yes
      with_items:
        - apache2
        - postgresql

    - name: Create nextcloud db user
      become_user: postgres
      postgresql_user:
        name: "{{ db_username }}"
        password: "{{ db_password }}"
        state: present

    - name: Create nextcloud db
      become_user: postgres
      postgresql_db:
        name: "{{ db_name }}"
        owner: "{{ db_username }}"
        state: present

    - name: Install Nextcloud dependencies
      apt:
        name: 
          - php-zip
          - php-xml
          - php-mbstring
          - php-gd
          - php-curl
          - php-pgsql
          - php-intl
          - php-imagick
          - php-gmp
          - php-bcmath
          - php-apcu
          - php-bz2
          - libmagickcore-6.q16-6-extra
        state: present
    
    - name: Copy nextcloud virtual host conf file
      copy:
        src: nextcloud.conf
        dest: /etc/apache2/sites-available/nextcloud.conf
        owner: root
        group: root
        mode: 0644

    - name: Enable nextcloud site
      command:
        cmd: a2ensite nextcloud
        creates: /etc/apache2/sites-enabled/nextcloud.conf
      notify: reload apache2

    - name: Enable required apache modules
      apache2_module:
        name: "{{ item }}"
        state: present
      with_items:
        - rewrite
        - headers
        - env
        - dir
        - mime
        - ssl
      notify: restart apache2

    - name: "Download nextcloud to {{ download_path }}"
      get_url:
        url: "{{ download_url }}"
        dest: "{{ download_path }}"
        checksum: "{{ checksum_url }}"

    - name: "Extract nextcloud to {{ www_folder }}"
      unarchive:
        src: "{{ download_path }}"
        dest: "{{ www_folder }}"
        remote_src: yes
        creates: "{{ www_folder }}/nextcloud"
      
    - name: "Copy nextcloud config file to {{ www_folder }}/nextcloud/config/config.php"
      copy:
        src: config.php
        dest: "{{ www_folder }}/nextcloud/config/config.php"
        owner: www-data
        group: www-data
        mode: 0640
        force: no
      
    - name: "Set owner of {{ www_folder }}/nextcloud to www-data"
      file:
        path: "{{ www_folder }}/nextcloud"
        owner: www-data
        group: www-data
        recurse: yes
      
    - name: "Create data folder {{ data_directory }}"
      file:
        path: "{{ data_directory }}"
        state: directory
        owner: www-data
        group: www-data

    - name: Setup cron job
      cron:
        name: Nextcloud cron
        user: www-data
        minute: "*/5"
        job: php -f {{ www_folder }}/nextcloud/cron.php --define apc.enable_cli=1
