services:
  navidrome:
    image: deluan/navidrome:latest
    container_name: navidrome
    restart: unless-stopped
    user: 1000:1000
    ports:
      - 127.0.0.1:4533:4533
    environment:
      ND_PORT: 4533
      ND_BASEURL: https://music.{{ main_domain }}
      ND_LASTFM_APIKEY: ${ND_LASTFM_APIKEY}
      ND_LASTFM_SECRET: ${ND_LASTFM_SECRET}
      ND_SPOTIFY_ID: ${ND_SPOTIFY_ID}
      ND_SPOTIFY_SECRET: ${ND_SPOTIFY_SECRET}
    volumes:
      - /nas/appdata/navidrome:/data
      - /nas/data/Music:/music:ro
