---
- { import_tasks: tmpfs.yml, tags: tmpfs }
- { import_tasks: mdadm.yml, tags: mdadm }
- { import_tasks: zfs.yml, tags: zfs }

- name: Add mount points for hard drives
  mount:
    src: "{{ item.device }}"
    path: "{{ item.path }}"
    fstype: "{{ item.fs }}"
    state: mounted
  loop: "{{ disks }}"

- name: Add bind mounts
  mount:
    src: "{{ item.src }}"
    path: "{{ item.mnt }}"
    opts: bind
    fstype: none
    state: mounted
  loop: "{{ bind_mounts }}"
