---
- name: Copy the raspi-reset and prepare-reset scripts
  template:
    src: "{{ item }}"
    dest: /usr/local/sbin/{{ item }}
    owner: root
    group: root
    mode: 0754
  loop:
    - prepare-reset
    - raspi-reset
